### ISSUE TITLE
Add sub-method to log directly?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/p-time#1]
Could be useful to be able to quickly log it directly in the console.

``` js
promiseTime.log(fn)();
```

What should the message look like?

Maybe:

``` js
console.log(`Promise from ${fn.name} resolved in ${promise.time} ms`);
```
## 

// @sotojuan

**Comment by sotojuan** [comment]
👍 I can make the PR later if you want.

**Comment by sindresorhus** [comment]
Sure, go ahead :)

**Comment by SamVerschueren** [comment]
Would be a very nice addition!
